[package]
name = "simulation"
version = "0.1.0"
edition = "2021"

authors = ["Adam"]
description = ""
license = "MIT"

[dependencies]
csv = "1.3.0"
rand = "0.8.5"
rand_distr = "0.4.3"

[[bin]]
name = "simulation"
path = "src/main.rs"
